### ISSUE TITLE
PSNR is not plotted with ADMM algorithm

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [carlosh93/9836_seismic_project#16]
![image](https://user-images.githubusercontent.com/66798186/182188176-e3be1ded-b408-4b46-ac1b-deb1f7e3c5aa.png)

it only happens with regular subsampling

**Comment by Enmartz** [comment]
This issue happens because the PSNR is infinite, then a message will be plotted when this kind of situation happens:
![image](https://user-images.githubusercontent.com/58752635/185177810-29957ac9-8afa-4101-acff-f3c7636ebcf6.png)

**Comment by Enmartz** [comment]
Issue fixed
![image](https://user-images.githubusercontent.com/58752635/185238985-a495b896-fcc4-4be4-87a8-1264b9ec7c8d.png)
