### ISSUE TITLE
Improve documentation for algorithms

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [carlosh93/9836_seismic_project#18]
This is unclear for a user non-familiarized with optimization algorithms. Make it more intuitive.

![image](https://user-images.githubusercontent.com/66798186/182193175-cdcac98b-2d68-49c9-b8a6-72d1220ab313.png)

**Comment by Enmartz** [comment]
Issue fixed
![image](https://user-images.githubusercontent.com/58752635/185250607-4265b1b5-dd95-4048-a8bd-6ba0a2941b6c.png)
