### ISSUE TITLE
Explain how the lists numbers have to be added

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [carlosh93/9836_seismic_project#19]
![image](https://user-images.githubusercontent.com/66798186/182194354-3804c2db-1fca-4fed-a892-81bdc58bf954.png)

explain how the selected traces have to be typed, for instance, numbers separated by commas, space, etc... Also, clarify that it must be integer numbers

**Comment by Enmartz** [comment]
**Issue fixed:**

A button was added to this subsampling option.
![image](https://user-images.githubusercontent.com/58752635/185257874-5a8f34dd-3fd8-48a2-b782-9c3315abfe3c.png)

The button displays a window with the instructions about this subsampling.
![image](https://user-images.githubusercontent.com/58752635/185257795-bfb180df-0003-4550-9e92-9276c7cac3f5.png)
