### ISSUE TITLE
Explain what does the seed means

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [carlosh93/9836_seismic_project#20]
for a non-programmer user, this is an unclear term. Clarify what the seed value means. 
![image](https://user-images.githubusercontent.com/66798186/182196382-57f2b87c-30e5-4d8f-a890-a348c1f178f3.png)

**Comment by Enmartz** [comment]
Issue fixed:

A help button was added to explain the use of the seed
![image](https://user-images.githubusercontent.com/58752635/185397257-bf3b7764-4e50-4e67-89b0-fc0556b685ce.png)
