### ISSUE TITLE
Incorrect link on documentation

### ISSUE THREAD

**Issue by cvcorreap** [carlosh93/9836_seismic_project#22]
1. What is the issue: In the documentation, the link of the image points to a void page (shown in the second image)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/94128275/183127302-c98857ea-339f-4a91-8cb9-344a53b70dde.png">
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/94128275/183127481-db1f7c26-8787-4ee6-b1f6-b9ddc46a1a0d.png">

2. How does that happen: When clicking the link

**Comment by Enmartz** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/58752635/185398768-4d85f86e-21e5-4e0b-bbd7-db34cf908fa8.png)
